name: fluxa
description: "Application de suivi dynamique de fluctuation des prix de produits dans différents marchés avec visualisation sur un graphique."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar: any
  fl_chart: ^1.1.1
  intl: ^0.20.2
  date_field: ^6.0.3+1
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/app_icon.png
  android_12:
    image: assets/logos/app_icon.png
    color: "#ffffff"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
